### PR TITLE
port to rtfm v0.4

### LINKED ISSUE #80: port to RTFM 0.4
Hello hello!

The next cortex-m-rtfm is out. But it is a major rework, so I would like to propose a roadmap.

Short-term, I would like to release the current PRs (#76, #77, #78) as follow:

- [x] fork ykomatsu's PR into a protected branch under either of our accounts
- [x] rebase and publish releases at each step

Long-term involves porting to cortex-m-rtfm 0.4

- [x] Fix the crate into 2018 edition (a requirement for rtfm 0.4, and can be started now)
- [x] Wait for svd2rust 0.14
- [x] Wait for the next stm32l1 made with svd2rust 0.14
- [x] Bump stm32l151-hal
- [x] Rework with cortex-m-rtfm 0.4

Going forward, the embedded WG is working on books and documentation
based on these newer crates. The porting effort is not easy, but I
hope clearer documentation can bring in more interest. I intend to
hook up an st-link v2, and if budget allows even get another AP1.

### PR DESCRIPTION
**Pull request by hdhoang**
The Reset action is temporarily not working.

closes #80.

### CODE REVIEW

**Comment by hdhoang** [comment]
hi @ah-, @japaric. Thank to your amazing foundational works, the port is going smoothly. Besides the little inconvenience below, I think it's good to merge.

Since `rtfm::Peripherals SCB` in `#[init]` is borrowed, I can't pass it down to `Keyboard` as a resource. The use-case I have is allowing the user to reset the key MCU with key inputs instead of having to flip over the board and poke the reset button (added in #45). Do you suppose I can pass it another way, or initiate a system-reset with another method (e.g. faking a press on the reset button)? My most frequently use of that reset is to put the bootloader into DFU mode, so setting up both the reset action and "holding down the Escape key" would be even better.

**Comment by hdhoang** [comment]
I have copied back the EXTI handlers and verified that DFU works

**Comment by japaric** [comment]
@hdhoang There's [`SCB.system_reset`](https://docs.rs/cortex-m/0.6.0/cortex_m/peripheral/struct.SCB.html#method.system_reset). However, it seems to require an instance of SCB; that seems unnecessary though since the operation only requires a volatile write. I would suggest sending a PR to the cortex-m crate adding a static `system_reset2` method (i.e. `SCB::system_reset2()`) to `SCB` and using that instead.

**Comment by hdhoang** [comment]
Got it, that route looks sensible. Thanks!

**Pull request merged**
