### PR TITLE
[CI] build non-master branches

### PR DESCRIPTION
**Pull request by hdhoang**
The environment variables are from https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

I have tested pushing to my `master`, and the tag came out correctly. https://api.travis-ci.org/v3/job/348145089/log.txt

```
++git tag 2018-03-02-14-master-4f584f0
```

I have yet to figure out how a PR's branch comes up. Please squash the commits before merging :)

### CODE REVIEW

**Comment by ah-** [comment]
Thanks! If we're building branches we might want to host our nightly build somewhere else instead of the GitHub release page. I just picked that since it was easy and I thought it was important to have binary dfu update files available.

But I'm not sure yet where to best upload nightlies. Tagged releases we probably still want on the GitHub page.

Anyways, this looks good, merging.

**Comment by Mange** [comment]
Right now I get one email on every push to master because I am watching and every new release sends out an email to all watchers.

This might also give reason to host nightlies somewhere else.

(Another reason is that releases here are meant to live forever AFAIK, and that will quickly fill up all lists after just a few months, making it hard to find actual stable releases when they start to appear.)

**Comment by ah-** [comment]
@Mange Sorry about all the emails yesterday when I was tinkering with mdbook/GitBooks!
I've got email notifications turned off, so don't quite feel the pain myself.

I just checked, and we can delete old useless releases here so can go through and clean up when the nightlies are moved. Still not sure where to move them though.

**Comment by Mange** [comment]
Heh, no problem. It takes literally 30 seconds to just archive all of them, so I'm not upset or anything. People live longer when they are less upset. 😂

Just wanted to mention it in case you were unaware. Sorry for not having anything more constructive to add, like a suggestion on where to move the artifacts.

**Pull request merged**
