### PR TITLE
travis: skip docs-only commit range

### LINKED ISSUE #2: [CI] don't push new release when only docs changed
Going forward, there will be a lot of docs PRs & commits. I will see if we can skip CI build and/or github release when only documentations are affected, under this whitelist

```
README.md
docs/*
```

### PR DESCRIPTION
**Pull request by hdhoang**
Adapted from facebook/react#2000 with the last state in https://github.com/facebook/react/commit/fc15d702b81f2edd608568733409918f8fa71763#diff-354f30a63fb0907d4ad57269548329e3L19

cf travis-ci/travis-ci#6301

Close #2.

### CODE REVIEW

**Comment by hdhoang** [comment]
This PR is unexpectedly skipped. I will force push more to investigate.

**Comment by hdhoang** [comment]
I have tested this out with https://travis-ci.org/hdhoang/anne-key/builds/347717687 (after also skipping `.yml`) and https://travis-ci.org/hdhoang/anne-key/builds/347718554

Unfortunately, this build was not tested at all and returned green https://travis-ci.org/hdhoang/anne-key/builds/347716273#L514 . I guess that `TRAVIS_COMMIT_RANGE` isn't updated after force-push. Let's see if `pipefail` helps.

**Comment by ah-** [comment]
Oh great, this is useful!

Do you think it's working now? Want me to merge?

**Comment by hdhoang** [comment]
I have verified that force-pushing fails when gated by the separate call to git. This use case is prolly not applicable to master anyhow.

After this is merged, I can make a PR from the test above to verify that this works, and someone should make some code change to verify that it doesn't break CI. 

But I want to ask about `only: master`. This means topic branches aren't CI-built in forks. Should we remove that and gate release to master-only some other way?

**Comment by ah-** [comment]
I think it worked!

https://travis-ci.org/ah-/anne-key/builds/348040808

About the `only: master`, I think there's no particular reason for it, just took some default. Please send a PR if you think it'd be better some other way.

**Pull request merged**
